"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-04

Creates all 12 tables. Hand-authored (not autogenerated) since this is the
first migration — there's no prior DB state to diff against, and the sandbox
this was built in has no live Postgres to autogenerate from. Column types
and constraints mirror app/models/*.py exactly; keep them in sync manually
if you edit models directly instead of via a new migration.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "merchants",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("business_category", sa.String(120), server_default="general"),
        sa.Column("currency", sa.String(8), server_default="INR"),
        sa.Column("created_at", sa.DateTime, nullable=False),
    )

    op.create_table(
        "products",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("merchant_id", sa.String(36), sa.ForeignKey("merchants.id"), nullable=False),
        sa.Column("sku", sa.String(64), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text, server_default=""),
        sa.Column("category", sa.String(120), server_default="general"),
        sa.Column("price", sa.Numeric(12, 2), nullable=False),
        sa.Column("currency", sa.String(8), server_default="INR"),
        sa.Column("inventory_count", sa.Integer, server_default="0"),
        sa.Column("is_active", sa.Boolean, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime, nullable=False),
    )
    op.create_index("ix_products_merchant_id", "products", ["merchant_id"])
    op.create_index("ix_products_category", "products", ["category"])

    op.create_table(
        "customers",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("merchant_id", sa.String(36), sa.ForeignKey("merchants.id"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime, nullable=False),
    )
    op.create_index("ix_customers_merchant_id", "customers", ["merchant_id"])

    op.create_table(
        "orders",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("merchant_id", sa.String(36), sa.ForeignKey("merchants.id"), nullable=False),
        sa.Column("customer_id", sa.String(36), sa.ForeignKey("customers.id"), nullable=True),
        sa.Column("status", sa.String(32), server_default="created"),
        sa.Column("total_amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("currency", sa.String(8), server_default="INR"),
        sa.Column("razorpay_order_id", sa.String(120), nullable=True),
        sa.Column("razorpay_payment_id", sa.String(120), nullable=True),
        sa.Column("source", sa.String(32), server_default="dashboard"),
        sa.Column("idempotency_key", sa.String(120), nullable=True, unique=True),
        sa.Column("created_at", sa.DateTime, nullable=False),
    )
    op.create_index("ix_orders_merchant_id", "orders", ["merchant_id"])
    op.create_index("ix_orders_customer_id", "orders", ["customer_id"])

    op.create_table(
        "order_items",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("order_id", sa.String(36), sa.ForeignKey("orders.id"), nullable=False),
        sa.Column("product_id", sa.String(36), sa.ForeignKey("products.id"), nullable=False),
        sa.Column("quantity", sa.Integer, server_default="1"),
        sa.Column("unit_price", sa.Numeric(12, 2), nullable=False),
    )
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"])
    op.create_index("ix_order_items_product_id", "order_items", ["product_id"])

    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("merchant_id", sa.String(36), sa.ForeignKey("merchants.id"), nullable=False),
        sa.Column("type", sa.String(32), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("target_category", sa.String(120), nullable=True),
        sa.Column("target_product_ids", postgresql.JSONB, server_default="[]"),
        sa.Column("discount_percent", sa.Numeric(5, 2), nullable=True),
        sa.Column("status", sa.String(32), server_default="draft"),
        sa.Column("reason", sa.String(1000), nullable=True),
        sa.Column("expected_impact", sa.String(500), nullable=True),
        sa.Column("created_at", sa.DateTime, nullable=False),
    )
    op.create_index("ix_campaigns_merchant_id", "campaigns", ["merchant_id"])

    op.create_table(
        "campaign_events",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("campaign_id", sa.String(36), sa.ForeignKey("campaigns.id"), nullable=False),
        sa.Column("event_type", sa.String(64), nullable=False),
        sa.Column("detail", postgresql.JSONB, server_default="{}"),
        sa.Column("created_at", sa.DateTime, nullable=False),
    )
    op.create_index("ix_campaign_events_campaign_id", "campaign_events", ["campaign_id"])

    op.create_table(
        "policies",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("merchant_id", sa.String(36), sa.ForeignKey("merchants.id"), nullable=False),
        sa.Column("key", sa.String(120), nullable=False),
        sa.Column("value", sa.String(255), nullable=False),
        sa.Column("description", sa.String(500), nullable=True),
        sa.Column("updated_at", sa.DateTime, nullable=False),
    )
    op.create_index("ix_policies_merchant_id", "policies", ["merchant_id"])

    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("merchant_id", sa.String(36), sa.ForeignKey("merchants.id"), nullable=False),
        sa.Column("request_text", sa.Text, nullable=False),
        sa.Column("intent", sa.String(120), nullable=True),
        sa.Column("status", sa.String(32), server_default="running"),
        sa.Column("recommendation", sa.Text, nullable=True),
        sa.Column("proposed_action", postgresql.JSONB, nullable=True),
        sa.Column("error", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime, nullable=False),
        sa.Column("completed_at", sa.DateTime, nullable=True),
    )
    op.create_index("ix_agent_runs_merchant_id", "agent_runs", ["merchant_id"])

    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("run_id", sa.String(36), sa.ForeignKey("agent_runs.id"), nullable=False),
        sa.Column("tool_name", sa.String(64), nullable=False),
        sa.Column("input", postgresql.JSONB, server_default="{}"),
        sa.Column("output_summary", sa.Text, nullable=True),
        sa.Column("latency_ms", sa.String(16), nullable=True),
        sa.Column("success", sa.Boolean, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime, nullable=False),
    )
    op.create_index("ix_tool_calls_run_id", "tool_calls", ["run_id"])

    op.create_table(
        "approvals",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("run_id", sa.String(36), sa.ForeignKey("agent_runs.id"), nullable=False),
        sa.Column("merchant_id", sa.String(36), sa.ForeignKey("merchants.id"), nullable=False),
        sa.Column("action_type", sa.String(64), nullable=False),
        sa.Column("action_payload", postgresql.JSONB, server_default="{}"),
        sa.Column("reason", sa.Text, nullable=True),
        sa.Column("expected_impact", sa.String(500), nullable=True),
        sa.Column("risk_level", sa.String(16), server_default="low"),
        sa.Column("policy_result", sa.String(16), server_default="pending"),
        sa.Column("policy_detail", sa.String(500), nullable=True),
        sa.Column("status", sa.String(16), server_default="pending"),
        sa.Column("decided_at", sa.DateTime, nullable=True),
        sa.Column("created_at", sa.DateTime, nullable=False),
    )
    op.create_index("ix_approvals_run_id", "approvals", ["run_id"])
    op.create_index("ix_approvals_merchant_id", "approvals", ["merchant_id"])

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("run_id", sa.String(36), sa.ForeignKey("agent_runs.id"), nullable=True),
        sa.Column("merchant_id", sa.String(36), sa.ForeignKey("merchants.id"), nullable=False),
        sa.Column("event_type", sa.String(64), nullable=False),
        sa.Column("summary", sa.Text, nullable=False),
        sa.Column("detail", postgresql.JSONB, server_default="{}"),
        sa.Column("razorpay_reference", sa.String(120), nullable=True),
        sa.Column("created_at", sa.DateTime, nullable=False),
    )
    op.create_index("ix_audit_logs_run_id", "audit_logs", ["run_id"])
    op.create_index("ix_audit_logs_merchant_id", "audit_logs", ["merchant_id"])


def downgrade() -> None:
    op.drop_table("audit_logs")
    op.drop_table("approvals")
    op.drop_table("tool_calls")
    op.drop_table("agent_runs")
    op.drop_table("policies")
    op.drop_table("campaign_events")
    op.drop_table("campaigns")
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_table("customers")
    op.drop_table("products")
    op.drop_table("merchants")